### ISSUE TITLE
Some error with example data and my own data in certain modules

### ISSUE THREAD

**Issue by DoYup** [kwanjeeraw/metabox#6]
There are some error messages. 
I tried to use example data and also data set created by me.
It would be appreciated if you could give me a advice.

1. BioNetwork (simple network and heterogeneous network)
- no network showed up with example data
- error message popped up with data set inputted by me. (UniprotKB with human proteins (200 proteins) and Pubchem CID (150 metabolites), saying "**In call: unserialize(node$con)**"

![image](https://user-images.githubusercontent.com/28615020/34317816-443acc20-e7fa-11e7-90ab-7dbd57d74c06.png)

2. Likewise, Overrepresentation analysis did not work with "pathway" and "mesh" at least for me.
- no network showed up with example data
- error message popped up with data set inputted by me. (UniprotKB with human proteins (200 proteins) OR Pubchem CID (150 metabolites), saying "**In call: order(attb$nodename, decreasing = TRUE)**"

![image](https://user-images.githubusercontent.com/28615020/34317843-124d7536-e7fb-11e7-98fb-11bac3837ee2.png)

**Comment by kwanjeeraw** [comment]
Hi,

1. The database server is no longer supported so the network functions won't return any result.
2. As far as I've checked, Overrepresentation analysis works only for compounds (with mesh annotation).

**Comment by DoYup** [comment]
Thanks for the answer.
Is there no alternative to use the database server? There are some modules that I would like to use (e.g.  Functional class scoring, overrepresentation analysis based on pathway....etc).

**Comment by kwanjeeraw** [comment]
Yes. You can install database locally by following the manual here
http://kwanjeeraw.github.io/metabox/metabox_manual_1-2.pdf

**Comment by DoYup** [comment]
Thank you!
