### ISSUE TITLE
Failed authentication attempt for neo4j

### ISSUE THREAD

**Issue by mjw77** [kwanjeeraw/metabox#8]
Hi Kwanjeeraw
I am keen to use the similarity tool in metabox. It shows me a network of compounds based on the PubChem IDs, however, when I select 'pathway' under Function Overview, it doesn't appear to work (the network disappears) and in the Neo4j console I get 'WARN  Failed authentication attempt for 'neo4j' from 127.0.0.1' appear.'

I downloaded neo4j-community-4.1.7-windows. I have put the graph.db in the 'databases' folder within the neo4j directory and followed the instructions in the manual (e.g. database.R file in Documents containing database.location = " http://localhost:7474/db/data/").

Any advice would be greatly appreciated.
Mike

**Comment by kwanjeeraw** [comment]
Hi Mike
Did you use the password grinn as stated here?
4) For the first installation of Neo4j, it requires users to setup the password. Go to
http://localhost:7474/browser/ for setting the password to grinn for the first use.

The following link contains precompiled human pathway database.
2) Download the precompiled database, extract and copy to your Neo4j directory
https://www.dropbox.com/s/it1b11fzrk9l0r7/human_v6.zip?dl=0

Thanks.
